export type CourseCategory =
  | "pharmacy"
  | "education"
  | "paramedical"
  | "design"
  | "media"
  | "arts"
  | "wellness"
  | "hospitality"
  | "business"
  | "ai";

export type CourseKind = "diploma" | "degree" | "certificate";

export type Course = {
  slug: string;
  name: string;
  nameHi: string;
  shortName: string;
  kind?: CourseKind;
  category: CourseCategory;
  duration: string;
  durationHi: string;
  eligibility: string;
  eligibilityHi: string;
  seats: number;
  rating: number;
  reviews: number;
  enrolled: string;
  learn: string[];
  learnHi: string[];
  careers: string[];
  careersHi: string[];
  image: string;
  overview: string;
  overviewHi: string;
  fees: string;
  mode: string;
};

export const CATEGORIES: {
  id: CourseCategory | "all";
  label: string;
  labelHi: string;
}[] = [
  { id: "all", label: "All", labelHi: "सभी" },
  { id: "ai", label: "AI & Technology", labelHi: "एआई व टेक्नोलॉजी" },
  { id: "design", label: "Design & Styling", labelHi: "डिज़ाइन व स्टाइलिंग" },
  { id: "media", label: "Media & Communication", labelHi: "मीडिया व संचार" },
  { id: "arts", label: "Performing & Visual Arts", labelHi: "कला" },
  { id: "wellness", label: "Health & Wellness", labelHi: "स्वास्थ्य व वेलनेस" },
  { id: "hospitality", label: "Lifestyle & Hospitality", labelHi: "हॉस्पिटैलिटी" },
  { id: "business", label: "Business & Management", labelHi: "बिज़नेस व प्रबंधन" },
  { id: "pharmacy", label: "Pharmacy", labelHi: "फार्मेसी" },
  { id: "education", label: "Education", labelHi: "शिक्षा" },
  { id: "paramedical", label: "Paramedical", labelHi: "पैरामेडिकल" },
];

export const PROGRAMME_KINDS: { id: CourseKind; label: string; labelHi: string }[] = [
  { id: "diploma", label: "Diploma", labelHi: "डिप्लोमा" },
  { id: "degree", label: "Degree", labelHi: "डिग्री" },
  { id: "certificate", label: "Certificate", labelHi: "सर्टिफिकेट" },
];

export function courseKind(course: Course): CourseKind {
  return course.kind ?? "diploma";
}

export function programmeLabel(kind: CourseKind, hi = false) {
  const row = PROGRAMME_KINDS.find((k) => k.id === kind)!;
  return hi ? row.labelHi : row.label;
}

export const COURSES: Course[] = [
  {
    slug: "d-pharma",
    name: "Diploma in Pharmacy",
    nameHi: "डिप्लोमा इन फार्मेसी",
    shortName: "D Pharma",
    category: "pharmacy",
    duration: "2 Years",
    durationHi: "2 वर्ष",
    eligibility: "10+2 with Physics, Chemistry and Biology/Mathematics",
    eligibilityHi: "10+2 भौतिकी, रसायन और जीव विज्ञान/गणित के साथ",
    seats: 60,
    rating: 4.6,
    reviews: 420,
    enrolled: "2,400+",
    learn: ["Dispensing", "Pharmacology", "Hospital Pharmacy", "Drug Store Mgmt"],
    learnHi: ["डिस्पेंसिंग", "फार्माकोलॉजी", "अस्पताल फार्मेसी", "ड्रग स्टोर प्रबंधन"],
    careers: ["Pharmacist", "Hospital Pharmacy", "Retail Pharmacy", "Medical Rep"],
    careersHi: ["फार्मासिस्ट", "अस्पताल फार्मेसी", "रिटेल फार्मेसी", "मेडिकल रेप"],
    image: "/photos/pharmacy.jpg",
    overview:
      "PCI-aligned Diploma in Pharmacy with hospital postings, dispensing practice and community pharmacy skills.",
    overviewHi:
      "अस्पताल पोस्टिंग, डिस्पेंसिंग अभ्यास और सामुदायिक फार्मेसी कौशल के साथ PCI-संरेखित डिप्लोमा इन फार्मेसी।",
    fees: "As per state fee committee",
    mode: "Full-time Diploma",
  },
  {
    slug: "d-el-ed",
    name: "Diploma in Elementary Education",
    nameHi: "डिप्लोमा इन एलिमेंटरी एजुकेशन",
    shortName: "D.El.Ed",
    category: "education",
    duration: "2 Years",
    durationHi: "2 वर्ष",
    eligibility: "10+2 with 50% as per NCTE norms",
    eligibilityHi: "एनसीटीई मानकों के अनुसार 10+2 में 50%",
    seats: 50,
    rating: 4.5,
    reviews: 310,
    enrolled: "1,800+",
    learn: ["Child Pedagogy", "Classroom Mgmt", "Lesson Planning", "School Internship"],
    learnHi: ["बाल पेडागॉजी", "कक्षा प्रबंधन", "पाठ योजना", "स्कूल इंटर्नशिप"],
    careers: ["Elementary Teacher", "PRT", "Special Educator", "School Coordinator"],
    careersHi: ["प्रारंभिक शिक्षक", "पीआरटी", "विशेष शिक्षक", "स्कूल समन्वयक"],
    image: "/photos/education.jpg",
    overview:
      "Diploma in Elementary Education with child-centred pedagogy and school-based internships.",
    overviewHi:
      "बाल-केंद्रित पेडागॉजी और स्कूल इंटर्नशिप के साथ डी.एल.एड।",
    fees: "Scholarship eligible",
    mode: "Full-time Diploma",
  },
  {
    slug: "btc",
    name: "Diploma in Basic Teaching",
    nameHi: "डिप्लोमा इन बेसिक टीचिंग",
    shortName: "BTC",
    category: "education",
    duration: "2 Years",
    durationHi: "2 वर्ष",
    eligibility: "Graduation as per latest NCTE/state norms",
    eligibilityHi: "नवीनतम एनसीटीई/राज्य मानकों के अनुसार स्नातक",
    seats: 50,
    rating: 4.4,
    reviews: 260,
    enrolled: "1,100+",
    learn: ["Primary Methods", "Hindi & EVS", "Inclusive Education", "Practice Teaching"],
    learnHi: ["प्राथमिक विधियाँ", "हिन्दी व ईवीएस", "समावेशी शिक्षा", "अभ्यास शिक्षण"],
    careers: ["Primary Teacher", "Upper Primary Teacher", "Govt School", "Edu Volunteer"],
    careersHi: ["प्राथमिक शिक्षक", "उच्च प्राथमिक शिक्षक", "सरकारी विद्यालय", "शिक्षा स्वयंसेवक"],
    image: "/photos/classroom.jpg",
    overview:
      "Diploma-level Basic Teaching Certificate preparing classroom-ready teachers for government and private schools.",
    overviewHi:
      "सरकारी और निजी विद्यालयों के लिए कक्षा-तैयार शिक्षक बनाने वाला डिप्लोमा-स्तरीय बीटीसी कार्यक्रम।",
    fees: "As notified each session",
    mode: "Full-time Diploma",
  },
  {
    slug: "dmlt",
    name: "Diploma in Medical Lab Technology",
    nameHi: "डिप्लोमा इन मेडिकल लैब टेक्नोलॉजी",
    shortName: "DMLT",
    category: "paramedical",
    duration: "2 Years",
    durationHi: "2 वर्ष",
    eligibility: "10+2 Science (PCB preferred)",
    eligibilityHi: "10+2 विज्ञान (PCB वांछनीय)",
    seats: 40,
    rating: 4.7,
    reviews: 380,
    enrolled: "1,650+",
    learn: ["Pathology", "Biochemistry", "Microbiology", "Blood Banking"],
    learnHi: ["पैथोलॉजी", "बायोकेमिस्ट्री", "माइक्रोबायोलॉजी", "ब्लड बैंकिंग"],
    careers: ["Lab Technician", "Pathology Assistant", "Blood Bank", "Diagnostic Centre"],
    careersHi: ["लैब टेक्नीशियन", "पैथोलॉजी असिस्टेंट", "ब्लड बैंक", "डायग्नोस्टिक सेंटर"],
    image: "/photos/medical.jpg",
    overview:
      "Diploma in Medical Laboratory Technology with diagnostic lab rotations and hospital exposure.",
    overviewHi:
      "डायग्नोस्टिक लैब रोटेशन और अस्पताल अनुभव के साथ डीएमएलटी।",
    fees: "Hospital partnership seats available",
    mode: "Full-time Diploma",
  },
  {
    slug: "x-ray-technician",
    name: "Diploma in X-Ray Technology",
    nameHi: "डिप्लोमा इन एक्स-रे टेक्नोलॉजी",
    shortName: "X-Ray Technician",
    category: "paramedical",
    duration: "2 Years",
    durationHi: "2 वर्ष",
    eligibility: "10+2 Science",
    eligibilityHi: "10+2 विज्ञान",
    seats: 30,
    rating: 4.3,
    reviews: 190,
    enrolled: "900+",
    learn: ["Radiography", "Imaging Safety", "Equipment Handling", "Clinical Posting"],
    learnHi: ["रेडियोग्राफी", "इमेजिंग सुरक्षा", "उपकरण संचालन", "क्लिनिकल पोस्टिंग"],
    careers: ["X-Ray Technician", "Radiology Assistant", "Diagnostic Centre", "Hospital Imaging"],
    careersHi: ["एक्स-रे टेक्नीशियन", "रेडियोलॉजी असिस्टेंट", "डायग्नोस्टिक सेंटर", "अस्पताल इमेजिंग"],
    image: "/photos/xray.jpg",
    overview:
      "Diploma in radiography covering imaging safety, equipment handling and clinical postings.",
    overviewHi:
      "इमेजिंग सुरक्षा, उपकरण संचालन और क्लिनिकल पोस्टिंग वाला रेडियोग्राफी डिप्लोमा।",
    fees: "As per session notification",
    mode: "Full-time Diploma",
  },
  {
    slug: "operation-theatre-technician",
    name: "Diploma in OT Technology",
    nameHi: "डिप्लोमा इन ओटी टेक्नोलॉजी",
    shortName: "OT Technician",
    category: "paramedical",
    duration: "2 Years",
    durationHi: "2 वर्ष",
    eligibility: "10+2 Science",
    eligibilityHi: "10+2 विज्ञान",
    seats: 30,
    rating: 4.4,
    reviews: 210,
    enrolled: "1,050+",
    learn: ["Sterilisation", "Surgical Support", "OT Protocols", "Critical Care"],
    learnHi: ["स्टेरिलाइजेशन", "सर्जिकल सपोर्ट", "ओटी प्रोटोकॉल", "क्रिटिकल केयर"],
    careers: ["OT Technician", "Surgical Assistant", "Emergency Care", "Hospital OT"],
    careersHi: ["ओटी टेक्नीशियन", "सर्जिकल असिस्टेंट", "इमरजेंसी केयर", "अस्पताल ओटी"],
    image: "/photos/surgery.jpg",
    overview:
      "Diploma in OT technology: sterilisation, surgical assistance protocols and critical-care support.",
    overviewHi:
      "स्टेरिलाइजेशन, सर्जिकल सहायता प्रोटोकॉल और क्रिटिकल-केयर सपोर्ट में ओटी डिप्लोमा।",
    fees: "Clinical posting included",
    mode: "Full-time Diploma",
  },
  {
    slug: "interior-design",
    name: "Diploma in Interior Design",
    nameHi: "डिप्लोमा इन इंटीरियर डिज़ाइन",
    shortName: "Interior Design",
    category: "design",
    duration: "1 Year",
    durationHi: "1 वर्ष",
    eligibility: "10+2 in any stream",
    eligibilityHi: "किसी भी स्ट्रीम में 10+2",
    seats: 40,
    rating: 4.3,
    reviews: 700,
    enrolled: "2,500+",
    learn: ["Auto CAD", "Vastu-shastra", "Design Styles", "Space Planning"],
    learnHi: ["ऑटो कैड", "वास्तु-शास्त्र", "डिज़ाइन स्टाइल", "स्पेस प्लानिंग"],
    careers: ["Interior Designer", "Corporate Designer", "Design Manager", "Visual Merchandiser"],
    careersHi: ["इंटीरियर डिज़ाइनर", "कॉर्पोरेट डिज़ाइनर", "डिज़ाइन मैनेजर", "विज़ुअल मर्चेंडाइज़र"],
    image: "/photos/interior.jpg",
    overview: "Studio-based interior diploma covering CAD, vastu, materials and live space-planning projects.",
    overviewHi: "कैड, वास्तु, सामग्री और लाइव स्पेस-प्लानिंग प्रोजेक्ट वाला इंटीरियर डिप्लोमा।",
    fees: "Tool kit included",
    mode: "Full-time Diploma",
  },
  {
    slug: "culinary-arts",
    name: "Diploma in Culinary Arts",
    nameHi: "डिप्लोमा इन कलिनरी आर्ट्स",
    shortName: "Culinary Arts",
    category: "hospitality",
    duration: "1 Year",
    durationHi: "1 वर्ष",
    eligibility: "10+2 in any stream",
    eligibilityHi: "किसी भी स्ट्रीम में 10+2",
    seats: 40,
    rating: 4.4,
    reviews: 300,
    enrolled: "1,100+",
    learn: ["Cost Control", "Food Science", "Menu Planning", "World Cuisine"],
    learnHi: ["कॉस्ट कंट्रोल", "फूड साइंस", "मेनू प्लानिंग", "वर्ल्ड कुज़ीन"],
    careers: ["Sous Chef", "Pastry Chef", "Food Stylist", "Executive Chef"],
    careersHi: ["सू शेफ", "पेस्ट्री शेफ", "फूड स्टाइलिस्ट", "एग्जीक्यूटिव शेफ"],
    image: "/photos/culinary.jpg",
    overview: "Professional kitchen diploma with bakery, world cuisine, hygiene and hotel internships.",
    overviewHi: "बेकरी, वर्ल्ड कुज़ीन, हाइजीन और होटल इंटर्नशिप वाला कलिनरी डिप्लोमा।",
    fees: "Chef uniform included",
    mode: "Full-time Diploma",
  },
  {
    slug: "fashion-design",
    name: "Diploma in Fashion Design",
    nameHi: "डिप्लोमा इन फैशन डिज़ाइन",
    shortName: "Fashion Design",
    category: "design",
    duration: "1 Year",
    durationHi: "1 वर्ष",
    eligibility: "10+2 in any stream",
    eligibilityHi: "किसी भी स्ट्रीम में 10+2",
    seats: 40,
    rating: 4.8,
    reviews: 840,
    enrolled: "2,300+",
    learn: ["CAD & Clo3D", "Merchandising", "Pattern Making", "Consumer Behavior"],
    learnHi: ["कैड व Clo3D", "मर्चेंडाइजिंग", "पैटर्न मेकिंग", "कंज्यूमर बिहेवियर"],
    careers: ["Fashion Blogger", "Fashion Stylist", "Fashion Designer", "Textile Designer"],
    careersHi: ["फैशन ब्लॉगर", "फैशन स्टाइलिस्ट", "फैशन डिज़ाइनर", "टेक्सटाइल डिज़ाइनर"],
    image: "/photos/fashion.jpg",
    overview: "Fashion diploma covering pattern making, draping, CAD and portfolio for industry internships.",
    overviewHi: "पैटर्न, ड्रेपिंग, कैड और इंडस्ट्री पोर्टफोलियो वाला फैशन डिप्लोमा।",
    fees: "Studio access included",
    mode: "Full-time Diploma",
  },
  {
    slug: "naturopathy",
    name: "Diploma in Naturopathy",
    nameHi: "डिप्लोमा इन नेचुरोपैथी",
    shortName: "Naturopathy",
    category: "wellness",
    duration: "1 Year",
    durationHi: "1 वर्ष",
    eligibility: "10+2 in any stream",
    eligibilityHi: "किसी भी स्ट्रीम में 10+2",
    seats: 30,
    rating: 4.1,
    reviews: 40,
    enrolled: "400+",
    learn: ["Naturopathic Anatomy", "Natural Nutrition", "Hydrotherapy", "Magnetotherapy"],
    learnHi: ["नेचुरोपैथिक एनाटॉमी", "प्राकृतिक पोषण", "हाइड्रोथेरेपी", "मैग्नेटोथेरेपी"],
    careers: ["Naturopathy Consultant", "Wellness Manager", "Nutrition Advisor", "Corporate Wellness Coach"],
    careersHi: ["नेचुरोपैथी कंसल्टेंट", "वेलनेस मैनेजर", "पोषण सलाहकार", "कॉर्पोरेट वेलनेस कोच"],
    image: "/photos/yoga.jpg",
    overview: "Natural-healing diploma with nutrition, hydrotherapy and wellness-centre internships.",
    overviewHi: "पोषण, हाइड्रोथेरेपी और वेलनेस-सेंटर इंटर्नशिप वाला नेचुरोपैथी डिप्लोमा।",
    fees: "Clinic posting included",
    mode: "Full-time Diploma",
  },
  {
    slug: "screenwriting",
    name: "Certificate in Screenwriting",
    nameHi: "सर्टिफिकेट इन स्क्रीनराइटिंग",
    shortName: "Screenwriting",
    kind: "certificate",
    category: "media",
    duration: "6 Months",
    durationHi: "6 माह",
    eligibility: "10+2 in any stream",
    eligibilityHi: "किसी भी स्ट्रीम में 10+2",
    seats: 30,
    rating: 4.4,
    reviews: 110,
    enrolled: "1,200+",
    learn: ["Story Structure", "Dialogue", "OTT Formats", "Pitch Decks"],
    learnHi: ["स्टोरी स्ट्रक्चर", "डायलॉग", "ओटीटी फॉर्मेट", "पिच डेक"],
    careers: ["Screenwriter", "Content Writer", "Script Editor", "Showrunner Assistant"],
    careersHi: ["स्क्रीनराइटर", "कंटेंट राइटर", "स्क्रिप्ट एडिटर", "शोरनर असिस्टेंट"],
    image: "/photos/film.jpg",
    overview: "Writing lab for films, web series and ads with mentor-led table reads.",
    overviewHi: "फिल्म, वेब सीरीज़ और विज्ञापन के लिए मेंटर-लीड राइटिंग लैब।",
    fees: "Portfolio review included",
    mode: "Full-time Diploma",
  },
  {
    slug: "psychology",
    name: "Diploma in Psychology",
    nameHi: "डिप्लोमा इन साइकोलॉजी",
    shortName: "Psychology",
    category: "wellness",
    duration: "1 Year",
    durationHi: "1 वर्ष",
    eligibility: "10+2 in any stream",
    eligibilityHi: "किसी भी स्ट्रीम में 10+2",
    seats: 40,
    rating: 4.8,
    reviews: 140,
    enrolled: "400+",
    learn: ["Counselling Skills", "Developmental Psych", "Assessment", "Ethics"],
    learnHi: ["काउंसलिंग स्किल्स", "डेवलपमेंटल साइक", "असेसमेंट", "एथिक्स"],
    careers: ["Counsellor Assistant", "HR Associate", "School Counsellor", "Wellness Coach"],
    careersHi: ["काउंसलर असिस्टेंट", "एचआर एसोसिएट", "स्कूल काउंसलर", "वेलनेस कोच"],
    image: "/photos/psychology.jpg",
    overview: "Applied psychology diploma for counselling, schools and workplace wellness roles.",
    overviewHi: "काउंसलिंग, स्कूल और वर्कप्लेस वेलनेस के लिए एप्लाइड साइकोलॉजी डिप्लोमा।",
    fees: "Practicum included",
    mode: "Full-time Diploma",
  },
  {
    slug: "makeup",
    name: "Certificate in Makeup",
    nameHi: "सर्टिफिकेट इन मेकअप",
    shortName: "Makeup",
    kind: "certificate",
    category: "design",
    duration: "6 Months",
    durationHi: "6 माह",
    eligibility: "10+2 in any stream",
    eligibilityHi: "किसी भी स्ट्रीम में 10+2",
    seats: 30,
    rating: 4.5,
    reviews: 50,
    enrolled: "450+",
    learn: ["Bridal Makeup", "Fashion Makeup", "SFX Basics", "Portfolio Shoots"],
    learnHi: ["ब्राइडल मेकअप", "फैशन मेकअप", "SFX बेसिक्स", "पोर्टफोलियो शूट"],
    careers: ["Makeup Artist", "Bridal Stylist", "Fashion MUA", "Salon Lead"],
    careersHi: ["मेकअप आर्टिस्ट", "ब्राइडल स्टाइलिस्ट", "फैशन एमयूए", "सैलून लीड"],
    image: "/photos/makeup.jpg",
    overview: "Hands-on makeup diploma for bridal, fashion and media looks with live shoots.",
    overviewHi: "ब्राइडल, फैशन और मीडिया लुक के लिए लाइव शूट वाला मेकअप डिप्लोमा।",
    fees: "Kit included",
    mode: "Full-time Diploma",
  },
  {
    slug: "photography",
    name: "Diploma in Photography",
    nameHi: "डिप्लोमा इन फोटोग्राफी",
    shortName: "Photography",
    category: "arts",
    duration: "1 Year",
    durationHi: "1 वर्ष",
    eligibility: "10+2 in any stream",
    eligibilityHi: "किसी भी स्ट्रीम में 10+2",
    seats: 30,
    rating: 4.6,
    reviews: 220,
    enrolled: "980+",
    learn: ["Camera Craft", "Lighting", "Photo Editing", "Fashion Shoots"],
    learnHi: ["कैमरा क्राफ्ट", "लाइटिंग", "फोटो एडिटिंग", "फैशन शूट"],
    careers: ["Photographer", "Photo Editor", "Fashion Photographer", "Content Creator"],
    careersHi: ["फोटोग्राफर", "फोटो एडिटर", "फैशन फोटोग्राफर", "कंटेंट क्रिएटर"],
    image: "/photos/photography.jpg",
    overview: "Visual arts diploma covering camera, lighting, editing and commercial shoots.",
    overviewHi: "कैमरा, लाइटिंग, एडिटिंग और कमर्शियल शूट वाला फोटोग्राफी डिप्लोमा।",
    fees: "Studio access included",
    mode: "Full-time Diploma",
  },
  {
    slug: "digital-marketing",
    name: "Certificate in Digital Marketing",
    nameHi: "सर्टिफिकेट इन डिजिटल मार्केटिंग",
    shortName: "Digital Marketing",
    kind: "certificate",
    category: "business",
    duration: "6 Months",
    durationHi: "6 माह",
    eligibility: "10+2 in any stream",
    eligibilityHi: "किसी भी स्ट्रीम में 10+2",
    seats: 50,
    rating: 4.5,
    reviews: 390,
    enrolled: "1,700+",
    learn: ["SEO & SEM", "Social Media", "Content Strategy", "Analytics"],
    learnHi: ["SEO व SEM", "सोशल मीडिया", "कंटेंट स्ट्रैटेजी", "एनालिटिक्स"],
    careers: ["Digital Marketer", "Social Media Manager", "SEO Executive", "Brand Associate"],
    careersHi: ["डिजिटल मार्केटर", "सोशल मीडिया मैनेजर", "SEO एक्जीक्यूटिव", "ब्रांड एसोसिएट"],
    image: "/photos/marketing.jpg",
    overview: "Industry diploma in SEO, paid ads, social and analytics with live brand projects.",
    overviewHi: "SEO, पेड ऐड्स, सोशल और एनालिटिक्स वाला लाइव ब्रांड प्रोजेक्ट डिप्लोमा।",
    fees: "Certification included",
    mode: "Full-time Diploma",
  },
  {
    slug: "artificial-intelligence",
    name: "Diploma in Artificial Intelligence",
    nameHi: "डिप्लोमा इन आर्टिफिशियल इंटेलिजेंस",
    shortName: "Artificial Intelligence",
    category: "ai",
    duration: "1 Year",
    durationHi: "1 वर्ष",
    eligibility: "10+2 with Mathematics/Computer preferred",
    eligibilityHi: "10+2 गणित/कंप्यूटर वांछनीय",
    seats: 60,
    rating: 4.7,
    reviews: 520,
    enrolled: "2,800+",
    learn: ["Python for AI", "Neural Networks", "Computer Vision", "NLP Basics"],
    learnHi: ["पायथन फॉर एआई", "न्यूरल नेटवर्क्स", "कंप्यूटर विज़न", "एनएलपी बेसिक्स"],
    careers: ["AI Associate", "ML Intern", "Automation Analyst", "AI Product Support"],
    careersHi: ["एआई एसोसिएट", "एमएल इंटर्न", "ऑटोमेशन एनालिस्ट", "एआई प्रोडक्ट सपोर्ट"],
    image: "/photos/ai.jpg",
    overview: "Foundation diploma in AI: Python, neural networks, vision and NLP with capstone projects.",
    overviewHi: "पायथन, न्यूरल नेटवर्क, विज़न और एनएलपी वाला एआई डिप्लोमा, कैपस्टोन प्रोजेक्ट के साथ।",
    fees: "Lab access included",
    mode: "Full-time Diploma",
  },
  {
    slug: "generative-ai",
    name: "Certificate in Generative AI",
    nameHi: "सर्टिफिकेट इन जनरेटिव एआई",
    shortName: "Generative AI",
    kind: "certificate",
    category: "ai",
    duration: "6 Months",
    durationHi: "6 माह",
    eligibility: "10+2 in any stream",
    eligibilityHi: "किसी भी स्ट्रीम में 10+2",
    seats: 50,
    rating: 4.8,
    reviews: 410,
    enrolled: "3,200+",
    learn: ["Prompt Engineering", "ChatGPT & LLMs", "AI Images/Video", "AI Workflows"],
    learnHi: ["प्रॉम्प्ट इंजीनियरिंग", "ChatGPT व LLM", "एआई इमेज/वीडियो", "एआई वर्कफ़्लो"],
    careers: ["Prompt Engineer", "GenAI Specialist", "Content Automator", "AI Trainer"],
    careersHi: ["प्रॉम्प्ट इंजीनियर", "GenAI स्पेशलिस्ट", "कंटेंट ऑटोमेटर", "एआई ट्रेनर"],
    image: "/photos/robot.jpg",
    overview: "Hands-on generative AI diploma for prompts, LLMs, image/video tools and workplace automation.",
    overviewHi: "प्रॉम्प्ट, एलएलएम, इमेज/वीडियो टूल और वर्कप्लेस ऑटोमेशन वाला जनरेटिव एआई डिप्लोमा।",
    fees: "Tool credits included",
    mode: "Full-time Diploma",
  },
  {
    slug: "data-science-ai",
    name: "Diploma in Data Science & AI",
    nameHi: "डिप्लोमा इन डेटा साइंस एंड एआई",
    shortName: "Data Science & AI",
    category: "ai",
    duration: "1 Year",
    durationHi: "1 वर्ष",
    eligibility: "10+2 with Mathematics preferred",
    eligibilityHi: "10+2 गणित वांछनीय",
    seats: 50,
    rating: 4.6,
    reviews: 360,
    enrolled: "1,900+",
    learn: ["Python & SQL", "Data Visualisation", "ML Models", "Business Insights"],
    learnHi: ["पायथन व SQL", "डेटा विज़ुअलाइज़ेशन", "एमएल मॉडल", "बिज़नेस इनसाइट्स"],
    careers: ["Data Analyst", "Junior Data Scientist", "BI Executive", "AI Analyst"],
    careersHi: ["डेटा एनालिस्ट", "जूनियर डेटा साइंटिस्ट", "BI एक्जीक्यूटिव", "एआई एनालिस्ट"],
    image: "/photos/data.jpg",
    overview: "Data-to-decision diploma covering SQL, visualisation, machine learning and AI dashboards.",
    overviewHi: "SQL, विज़ुअलाइज़ेशन, मशीन लर्निंग और एआई डैशबोर्ड वाला डेटा साइंस डिप्लोमा।",
    fees: "Capstone included",
    mode: "Full-time Diploma",
  },
  {
    slug: "machine-learning",
    name: "Diploma in Machine Learning",
    nameHi: "डिप्लोमा इन मशीन लर्निंग",
    shortName: "Machine Learning",
    category: "ai",
    duration: "1 Year",
    durationHi: "1 वर्ष",
    eligibility: "10+2 with Mathematics/Computer preferred",
    eligibilityHi: "10+2 गणित/कंप्यूटर वांछनीय",
    seats: 40,
    rating: 4.5,
    reviews: 280,
    enrolled: "1,450+",
    learn: ["Supervised ML", "Unsupervised ML", "Model Deployment", "Python Libraries"],
    learnHi: ["सुपरवाइज्ड एमएल", "अनसुपरवाइज्ड एमएल", "मॉडल डिप्लॉयमेंट", "पायथन लाइब्रेरी"],
    careers: ["ML Engineer Intern", "Python Developer", "Model Tester", "AI Ops Associate"],
    careersHi: ["एमएल इंजीनियर इंटर्न", "पायथन डेवलपर", "मॉडल टेस्टर", "एआई ऑप्स एसोसिएट"],
    image: "/photos/chips.jpg",
    overview: "ML diploma from data prep to model training, evaluation and basic cloud deployment.",
    overviewHi: "डेटा तैयारी से मॉडल ट्रेनिंग, मूल्यांकन और बेसिक क्लाउड डिप्लॉयमेंट तक एमएल डिप्लोमा।",
    fees: "Cloud lab included",
    mode: "Full-time Diploma",
  },
  {
    slug: "ai-chatbots",
    name: "Certificate in AI Chatbots",
    nameHi: "सर्टिफिकेट इन एआई चैटबॉट्स",
    shortName: "AI Chatbots",
    kind: "certificate",
    category: "ai",
    duration: "6 Months",
    durationHi: "6 माह",
    eligibility: "10+2 in any stream",
    eligibilityHi: "किसी भी स्ट्रीम में 10+2",
    seats: 40,
    rating: 4.4,
    reviews: 190,
    enrolled: "1,100+",
    learn: ["Conversational AI", "Bot Design", "WhatsApp/API Bots", "Customer Automation"],
    learnHi: ["कन्वर्सेशनल एआई", "बॉट डिज़ाइन", "व्हाट्सएप/एपीआई बॉट", "कस्टमर ऑटोमेशन"],
    careers: ["Chatbot Developer", "CX Automation", "Support AI Lead", "No-code Bot Builder"],
    careersHi: ["चैटबॉट डेवलपर", "सीएक्स ऑटोमेशन", "सपोर्ट एआई लीड", "नो-कोड बॉट बिल्डर"],
    image: "/photos/chatbot.jpg",
    overview: "Build AI chatbots for web, WhatsApp and CRM using LLMs and no-code plus Python paths.",
    overviewHi: "वेब, व्हाट्सएप और सीआरएम के लिए एलएलएम, नो-कोड और पायथन से एआई चैटबॉट बनाना।",
    fees: "Live bot project included",
    mode: "Certificate",
  },
  {
    slug: "b-pharma",
    name: "Bachelor of Pharmacy",
    nameHi: "बैचलर ऑफ फार्मेसी",
    shortName: "B.Pharm",
    kind: "degree",
    category: "pharmacy",
    duration: "4 Years",
    durationHi: "4 वर्ष",
    eligibility: "10+2 with PCB/PCM as per PCI norms",
    eligibilityHi: "पीसीआई मानकों के अनुसार 10+2 पीसीबी/पीसीएम",
    seats: 60,
    rating: 4.7,
    reviews: 210,
    enrolled: "900+",
    learn: ["Pharmaceutics", "Pharmacology", "Industrial Pharmacy", "Clinical Practice"],
    learnHi: ["फार्मास्यूटिक्स", "फार्माकोलॉजी", "इंडस्ट्रियल फार्मेसी", "क्लिनिकल प्रैक्टिस"],
    careers: ["Pharmacist", "Drug Inspector path", "Hospital Pharmacist", "Pharma Industry"],
    careersHi: ["फार्मासिस्ट", "ड्रग इंस्पेक्टर मार्ग", "अस्पताल फार्मासिस्ट", "फार्मा उद्योग"],
    image: "/photos/pharmacy.jpg",
    overview: "PCI-aligned B.Pharm degree with hospital postings and industry exposure after a strong diploma foundation.",
    overviewHi: "अस्पताल पोस्टिंग और उद्योग अनुभव के साथ पीसीआई-संरेखित बी.फार्म डिग्री।",
    fees: "As per state fee committee",
    mode: "Full-time Degree",
  },
  {
    slug: "b-ed",
    name: "Bachelor of Education",
    nameHi: "बैचलर ऑफ एजुकेशन",
    shortName: "B.Ed",
    kind: "degree",
    category: "education",
    duration: "2 Years",
    durationHi: "2 वर्ष",
    eligibility: "Graduation with 50% as per NCTE norms",
    eligibilityHi: "एनसीटीई मानकों के अनुसार स्नातक में 50%",
    seats: 50,
    rating: 4.6,
    reviews: 180,
    enrolled: "750+",
    learn: ["Pedagogy", "Inclusive Education", "Assessment", "School Internship"],
    learnHi: ["पेडागॉजी", "समावेशी शिक्षा", "असेसमेंट", "स्कूल इंटर्नशिप"],
    careers: ["TGT", "PGT pathway", "School Coordinator", "Education Officer track"],
    careersHi: ["टीजीटी", "पीजीटी मार्ग", "स्कूल समन्वयक", "शिक्षा अधिकारी मार्ग"],
    image: "/photos/education.jpg",
    overview: "NCTE-aligned B.Ed for classroom-ready teachers, building on GBTE’s diploma teacher-training pathway.",
    overviewHi: "कक्षा-तैयार शिक्षकों के लिए एनसीटीई-संरेखित बी.एड।",
    fees: "Scholarship eligible",
    mode: "Full-time Degree",
  },
  {
    slug: "bsc-mlt",
    name: "B.Sc. Medical Lab Technology",
    nameHi: "बी.एससी. मेडिकल लैब टेक्नोलॉजी",
    shortName: "B.Sc. MLT",
    kind: "degree",
    category: "paramedical",
    duration: "3 Years",
    durationHi: "3 वर्ष",
    eligibility: "10+2 PCB or DMLT lateral entry as per norms",
    eligibilityHi: "10+2 पीसीबी या मानकों के अनुसार डीएमएलटी लेटरल एंट्री",
    seats: 40,
    rating: 4.6,
    reviews: 160,
    enrolled: "620+",
    learn: ["Clinical Biochemistry", "Microbiology", "Haematology", "Lab Quality"],
    learnHi: ["क्लिनिकल बायोकेमिस्ट्री", "माइक्रोबायोलॉजी", "हेमेटोलॉजी", "लैब क्वालिटी"],
    careers: ["Lab Technologist", "Diagnostic Centre", "Hospital Lab", "Quality Analyst"],
    careersHi: ["लैब टेक्नोलॉजिस्ट", "डायग्नोस्टिक सेंटर", "अस्पताल लैब", "क्वालिटी एनालिस्ट"],
    image: "/photos/medical.jpg",
    overview: "Degree-level medical laboratory science with hospital-linked training after DMLT or 10+2 science.",
    overviewHi: "डीएमएलटी या 10+2 साइंस के बाद अस्पताल प्रशिक्षण के साथ मेडिकल लैब डिग्री।",
    fees: "Lab kit included",
    mode: "Full-time Degree",
  },
  {
    slug: "bba",
    name: "Bachelor of Business Administration",
    nameHi: "बैचलर ऑफ बिज़नेस एडमिनिस्ट्रेशन",
    shortName: "BBA",
    kind: "degree",
    category: "business",
    duration: "3 Years",
    durationHi: "3 वर्ष",
    eligibility: "10+2 in any stream",
    eligibilityHi: "किसी भी स्ट्रीम में 10+2",
    seats: 60,
    rating: 4.5,
    reviews: 140,
    enrolled: "800+",
    learn: ["Management", "Marketing", "Finance Basics", "Entrepreneurship"],
    learnHi: ["प्रबंधन", "मार्केटिंग", "फाइनेंस बेसिक्स", "उद्यमिता"],
    careers: ["Management Trainee", "Sales Executive", "Operations Associate", "Startup roles"],
    careersHi: ["मैनेजमेंट ट्रेनी", "सेल्स एग्जीक्यूटिव", "ऑपरेशन्स एसोसिएट", "स्टार्टअप भूमिकाएँ"],
    image: "/photos/marketing.jpg",
    overview: "A career-facing BBA with live projects, internships and a clear path after GBTE business diplomas.",
    overviewHi: "लाइव प्रोजेक्ट और इंटर्नशिप के साथ करियर-उन्मुख बीबीए।",
    fees: "Internship support included",
    mode: "Full-time Degree",
  },
  {
    slug: "bca-ai",
    name: "BCA in Artificial Intelligence",
    nameHi: "बीसीए इन आर्टिफिशियल इंटेलिजेंस",
    shortName: "BCA (AI)",
    kind: "degree",
    category: "ai",
    duration: "3 Years",
    durationHi: "3 वर्ष",
    eligibility: "10+2 with Mathematics/Computer preferred",
    eligibilityHi: "10+2 गणित/कंप्यूटर वांछनीय",
    seats: 40,
    rating: 4.7,
    reviews: 120,
    enrolled: "540+",
    learn: ["Programming", "AI Foundations", "Data Systems", "Capstone Project"],
    learnHi: ["प्रोग्रामिंग", "एआई फाउंडेशन", "डेटा सिस्टम", "कैपस्टोन प्रोजेक्ट"],
    careers: ["Junior Developer", "AI Associate", "Data Analyst", "Product Support"],
    careersHi: ["जूनियर डेवलपर", "एआई एसोसिएट", "डेटा एनालिस्ट", "प्रोडक्ट सपोर्ट"],
    image: "/photos/ai.jpg",
    overview: "Three-year degree in computing and AI for students moving up from GBTE technology diplomas.",
    overviewHi: "जीबीटीई टेक्नोलॉजी डिप्लोमा के बाद कंप्यूटिंग और एआई की तीन-वर्षीय डिग्री।",
    fees: "Lab access included",
    mode: "Full-time Degree",
  },
];

export function getCourse(slug: string) {
  return COURSES.find((course) => course.slug === slug);
}

export function getCoursesByCategory(category: CourseCategory | "all") {
  if (category === "all") return COURSES;
  return COURSES.filter((course) => course.category === category);
}
