export const SITE = {
  name: "GBET",
  shortName: "GBET",
  fullName: "Gautam Buddha Technical Education Group",
  trust: "Gautam Buddha Educational Trust",
  tagline: "Transform Your Future Through Quality Education",
  taglineHi: "गुणवत्तापूर्ण शिक्षा के साथ अपना भविष्य बदलें",
  url: "https://gbte.in",
  phone: "+91 9355470710",
  phoneTel: "+919355470710",
  email: "admission@gbedutrust.com",
  whatsapp: "919355470710",
  year: "2027",
} as const;

export const CAMPUSES = [
  {
    id: "noida",
    name: "Noida Campus",
    nameHi: "नोएडा परिसर",
    role: "Headquarters",
    address: "C-77, Sector 63A, Noida, Uttar Pradesh",
    mapQuery: "C-77, Sector 63A, Noida, Uttar Pradesh",
    image: "/photos/campus-noida.jpg",
  },
] as const;

export const SOCIAL = [
  { name: "Facebook", href: "https://facebook.com/gbteofficial" },
  { name: "Instagram", href: "https://instagram.com/gbteofficial" },
  { name: "LinkedIn", href: "https://linkedin.com/company/gbte" },
  { name: "YouTube", href: "https://youtube.com/@gbteofficial" },
] as const;

export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
] as const;

export const HIRING_COMPANIES = [
  "TCS",
  "Wipro",
  "HCL",
  "Infosys",
  "Apollo",
  "Fortis",
  "Medanta",
  "Cipla",
  "Sun Pharma",
  "Deloitte",
  "Kendriya Vidyalaya",
  "UP Govt. School",
] as const;
